package generator

import (
	. "github.com/dave/jennifer/jen"
)

func (g *Generator) genfile_doc() (*OutputFile, error) {
	file := NewFile(g.options.Package)
	file.HeaderComment("Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.")
	file.HeaderComment("This file contains documentation and example usage for the generated code.")

	// TODO:
	// - example usage
	// - documentation

	file.Line().Line()

	if len(g.idl.Docs) == 0 {
		file.Comment("No documentation available from the IDL.")
		file.Comment("Please refer to the IDL source or the program documentation for more information.")
		file.Line()
	} else {
		file.Comment("Documentation from the IDL:")
		for _, comment := range g.idl.Docs {
			file.Comment(comment)
		}
	}

	return &OutputFile{
		Name: "doc.go",
		File: file,
	}, nil
}
