package generator

import (
	. "github.com/dave/jennifer/jen"
)

func (g *Generator) gen_fetchers() (*OutputFile, error) {
	file := NewFile(g.options.Package)
	file.HeaderComment("Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.")
	file.HeaderComment("This file contains fetcher functions.")
	{
	}
	return &OutputFile{
		Name: "fetchers.go",
		File: file,
	}, nil
}
