package generator

import (
	. "github.com/dave/jennifer/jen"
	"github.com/gagliardetto/solana-go"
)

// TODO:
// - generate program IDs for mainnet, devnet, testnet, and localnet.

func (g *Generator) genfile_programID(id solana.PublicKey) (*OutputFile, error) {
	file := NewFile(g.options.Package)
	file.HeaderComment("Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.")
	file.HeaderComment("This file contains the program ID.")

	{
		idDecl := Var().Id("ProgramID").Op("=").Qual(PkgSolanaGo, "MustPublicKeyFromBase58").Call(Lit(id.String()))
		file.Add(idDecl)
	}

	return &OutputFile{
		Name: "program-id.go",
		File: file,
	}, nil
}
