on: [push, pull_request]
name: tests
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.24.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Pull from lfs
        run: git lfs pull
      - name: Test
        run: go test ./... -count=1
